apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-auth-config
  namespace: fintech
data:
  NODE_ENV: "production"
  PORT: "4001"
  OTP_TTL_MINUTES: "10"
  AUTH_SERVICE_URL: "http://auth-service"
  TRANSACTION_SERVICE_URL: "http://transaction-service"