apiVersion: v1
kind: Secret
metadata:
  name: fintech-auth-secret
  namespace: fintech
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_Jxe3NEQoj1uc@ep-flat-voice-a12c1829-pooler.ap-southeast-1.aws.neon.tech/neondb?schema=auth&sslmode=require&channel_binding=require"
  JWT_SECRET: "12345"
  SMTP_HOST: smtp.gmail.com         
  SMTP_PORT: "587"       
  SMTP_SECURE: "false"     
  SMTP_USER: info@ev91riderz.com        
  SMTP_PASS: hkftkhrpfqjysgnj       
  FROM_EMAIL: info@ev91riderz.com