apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fintech
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
      - name: transaction-service
        image: asia-south1-docker.pkg.dev/gen-lang-client-0520338057/fintech-repo/transaction-service:latest
        ports:
        - containerPort: 4003
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"