apiVersion: v1
kind: Secret
metadata:
  name: fintech-transaction-secret
  namespace: fintech
type: Opaque
stringData:
  DATABASE_URL: "postgresql://neondb_owner:npg_Jxe3NEQoj1uc@ep-flat-voice-a12c1829-pooler.ap-southeast-1.aws.neon.tech/neondb?schema=transactions&sslmode=require&channel_binding=require"
  JWT_SECRET: "12345"