apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: fintech
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: asia-south1-docker.pkg.dev/fintech-prod/fintech-repo/auth-service:latest
        ports:
        - containerPort: 4001
        envFrom:
        - configMapRef:
            name: fintech-auth-config
        - secretRef:
            name: fintech-auth-secret
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"