apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-transaction-config
  namespace: fintech
data:
  NODE_ENV: "production"
  PORT: 4003
  AUTH_SERVICE_URL: "http://auth-service"
  TRANSACTION_SERVICE_URL: "http://transaction-service"